# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# command to install dependencies
install:
  - "pip install coveralls"
  - "if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi"

# command to run tests
script:
  coverage run -a ./runtests.py
  coverage report

after_success:
  coveralls
